CREATE TABLE cities (
  id UUID PRIMARY KEY, name VARCHAR(32) NOT NULL UNIQUE, owner_id UUID NOT NULL,
  level SMALLINT NOT NULL CHECK (level BETWEEN 1 AND 6), population INTEGER NOT NULL CHECK (population >= 0),
  prosperity SMALLINT NOT NULL CHECK (prosperity BETWEEN 0 AND 100), civilization SMALLINT NOT NULL CHECK (civilization BETWEEN 0 AND 100),
  created_at TIMESTAMPTZ NOT NULL, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE city_members (city_id UUID NOT NULL REFERENCES cities(id), player_id UUID NOT NULL, role VARCHAR(32) NOT NULL, joined_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(city_id, player_id), UNIQUE(player_id));
CREATE TABLE city_roles (city_id UUID NOT NULL REFERENCES cities(id), role_key VARCHAR(32) NOT NULL, permissions JSONB NOT NULL, PRIMARY KEY(city_id, role_key));
CREATE TABLE city_invitations (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), player_id UUID NOT NULL, status VARCHAR(16) NOT NULL, expires_at TIMESTAMPTZ NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE city_claims (city_id UUID REFERENCES cities(id), world_id UUID NOT NULL, chunk_x INTEGER NOT NULL, chunk_z INTEGER NOT NULL, state VARCHAR(16) NOT NULL, influence INTEGER NOT NULL DEFAULT 0, lead_cycles INTEGER NOT NULL DEFAULT 0, version BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(world_id, chunk_x, chunk_z));
CREATE INDEX idx_city_claims_city ON city_claims(city_id);
CREATE TABLE city_buildings (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), category VARCHAR(32) NOT NULL, district_key VARCHAR(64), bounds JSONB NOT NULL, integrity SMALLINT NOT NULL CHECK(integrity BETWEEN 0 AND 100), status VARCHAR(24) NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE city_upgrades (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), upgrade_key VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, progress BIGINT NOT NULL DEFAULT 0, version BIGINT NOT NULL DEFAULT 0, UNIQUE(city_id, upgrade_key));

CREATE TABLE accounts (id UUID PRIMARY KEY, owner_type VARCHAR(24) NOT NULL, owner_id UUID NOT NULL, balance_minor BIGINT NOT NULL CHECK(balance_minor >= 0), version BIGINT NOT NULL DEFAULT 0, UNIQUE(owner_type, owner_id));
CREATE TABLE ledger_entries (id UUID PRIMARY KEY, account_id UUID NOT NULL REFERENCES accounts(id), actor_id UUID, entry_type VARCHAR(48) NOT NULL, amount_minor BIGINT NOT NULL, balance_after_minor BIGINT NOT NULL CHECK(balance_after_minor >= 0), reference_id UUID, idempotency_key UUID NOT NULL UNIQUE, occurred_at TIMESTAMPTZ NOT NULL);
CREATE INDEX idx_ledger_account_time ON ledger_entries(account_id, occurred_at DESC);
CREATE TABLE warehouses (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), building_id UUID REFERENCES city_buildings(id), capacity BIGINT NOT NULL CHECK(capacity >= 0), status VARCHAR(24) NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE warehouse_stock (warehouse_id UUID NOT NULL REFERENCES warehouses(id), commodity_key VARCHAR(96) NOT NULL, available_quantity BIGINT NOT NULL CHECK(available_quantity >= 0), reserved_quantity BIGINT NOT NULL CHECK(reserved_quantity >= 0), version BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(warehouse_id, commodity_key));
CREATE TABLE stock_reservations (id UUID PRIMARY KEY, warehouse_id UUID NOT NULL REFERENCES warehouses(id), owner_type VARCHAR(24) NOT NULL, owner_id UUID NOT NULL, commodity_key VARCHAR(96) NOT NULL, quantity BIGINT NOT NULL CHECK(quantity > 0), consumed BIGINT NOT NULL DEFAULT 0 CHECK(consumed >= 0), status VARCHAR(24) NOT NULL, expires_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE market_orders (id UUID PRIMARY KEY, owner_id UUID NOT NULL, settlement_id UUID NOT NULL REFERENCES cities(id), side VARCHAR(8) NOT NULL, commodity_key VARCHAR(96) NOT NULL, quantity BIGINT NOT NULL CHECK(quantity > 0), remaining_quantity BIGINT NOT NULL CHECK(remaining_quantity >= 0), unit_price_minor BIGINT NOT NULL CHECK(unit_price_minor > 0), status VARCHAR(24) NOT NULL, created_at TIMESTAMPTZ NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE INDEX idx_market_match ON market_orders(settlement_id, commodity_key, side, status, unit_price_minor, created_at);
CREATE TABLE trades (id UUID PRIMARY KEY, buy_order_id UUID NOT NULL REFERENCES market_orders(id), sell_order_id UUID NOT NULL REFERENCES market_orders(id), quantity BIGINT NOT NULL CHECK(quantity > 0), unit_price_minor BIGINT NOT NULL CHECK(unit_price_minor > 0), occurred_at TIMESTAMPTZ NOT NULL);
CREATE TABLE production_orders (id UUID PRIMARY KEY, building_id UUID NOT NULL REFERENCES city_buildings(id), recipe_key VARCHAR(96) NOT NULL, requested_quantity INTEGER NOT NULL CHECK(requested_quantity > 0), completed_quantity INTEGER NOT NULL DEFAULT 0, status VARCHAR(32) NOT NULL, priority INTEGER NOT NULL, progress_units BIGINT NOT NULL DEFAULT 0, created_by UUID NOT NULL, created_at TIMESTAMPTZ NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE contracts (id UUID PRIMARY KEY, issuer_id UUID NOT NULL, assignee_id UUID, contract_type VARCHAR(32) NOT NULL, terms JSONB NOT NULL, status VARCHAR(24) NOT NULL, deadline TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0);

CREATE TABLE campaigns (id UUID PRIMARY KEY, attacker_city_id UUID NOT NULL REFERENCES cities(id), defender_city_id UUID NOT NULL REFERENCES cities(id), campaign_type VARCHAR(24) NOT NULL, phase VARCHAR(24) NOT NULL, declared_at TIMESTAMPTZ NOT NULL, active_at TIMESTAMPTZ, ended_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0, CHECK(attacker_city_id <> defender_city_id));
CREATE TABLE campaign_objectives (id UUID PRIMARY KEY, campaign_id UUID NOT NULL REFERENCES campaigns(id), objective_type VARCHAR(32) NOT NULL, state VARCHAR(24) NOT NULL, world_id UUID NOT NULL, bounds JSONB NOT NULL, progress BIGINT NOT NULL DEFAULT 0, target BIGINT NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE breach_spends (id UUID PRIMARY KEY, campaign_id UUID NOT NULL REFERENCES campaigns(id), points INTEGER NOT NULL CHECK(points > 0), occurred_at TIMESTAMPTZ NOT NULL);
CREATE INDEX idx_breach_window ON breach_spends(campaign_id, occurred_at);
CREATE TABLE damage_journal (id UUID PRIMARY KEY, campaign_id UUID NOT NULL REFERENCES campaigns(id), city_id UUID NOT NULL REFERENCES cities(id), building_id UUID REFERENCES city_buildings(id), world_id UUID NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, z INTEGER NOT NULL, original_data TEXT NOT NULL, damaged_data TEXT NOT NULL, source_id UUID, cause VARCHAR(32) NOT NULL, repair_state VARCHAR(24) NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, UNIQUE(campaign_id, world_id, x, y, z));

CREATE TABLE repair_orders (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), campaign_id UUID NOT NULL REFERENCES campaigns(id), priority VARCHAR(16) NOT NULL, status VARCHAR(32) NOT NULL, estimate_minor BIGINT NOT NULL CHECK(estimate_minor >= 0), total_tasks INTEGER NOT NULL CHECK(total_tasks > 0), completed_tasks INTEGER NOT NULL DEFAULT 0, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE repair_tasks (id UUID PRIMARY KEY, repair_order_id UUID NOT NULL REFERENCES repair_orders(id), world_id UUID NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, z INTEGER NOT NULL, expected_current TEXT NOT NULL, target_data TEXT NOT NULL, commodity_key VARCHAR(96) NOT NULL, layer VARCHAR(24) NOT NULL, status VARCHAR(24) NOT NULL, lease_owner UUID, lease_expires_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0, UNIQUE(repair_order_id, world_id, x, y, z));
CREATE TABLE task_dependencies (task_id UUID NOT NULL REFERENCES repair_tasks(id), depends_on UUID NOT NULL REFERENCES repair_tasks(id), PRIMARY KEY(task_id, depends_on), CHECK(task_id <> depends_on));
CREATE TABLE builder_depots (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), building_id UUID NOT NULL REFERENCES city_buildings(id), tier INTEGER NOT NULL, capacity_units BIGINT NOT NULL, status VARCHAR(24) NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE material_reservations (id UUID PRIMARY KEY, repair_order_id UUID NOT NULL REFERENCES repair_orders(id), source_type VARCHAR(24) NOT NULL, source_id UUID NOT NULL, commodity_key VARCHAR(96) NOT NULL, reserved_quantity BIGINT NOT NULL CHECK(reserved_quantity > 0), consumed_quantity BIGINT NOT NULL DEFAULT 0, status VARCHAR(24) NOT NULL, expires_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE construction_transfers (id UUID PRIMARY KEY, repair_order_id UUID NOT NULL REFERENCES repair_orders(id), source_warehouse_id UUID NOT NULL REFERENCES warehouses(id), destination_depot_id UUID NOT NULL REFERENCES builder_depots(id), status VARCHAR(24) NOT NULL, route_id UUID, departed_at TIMESTAMPTZ, arrived_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE work_packages (id UUID PRIMARY KEY, repair_order_id UUID NOT NULL REFERENCES repair_orders(id), worker_id UUID, status VARCHAR(24) NOT NULL, expires_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE material_consumptions (id UUID PRIMARY KEY, reservation_id UUID NOT NULL REFERENCES material_reservations(id), repair_task_id UUID NOT NULL REFERENCES repair_tasks(id), status VARCHAR(24) NOT NULL, prepared_at TIMESTAMPTZ NOT NULL, committed_at TIMESTAMPTZ, UNIQUE(repair_task_id));

CREATE TABLE workers (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), profession VARCHAR(32) NOT NULL, skill SMALLINT NOT NULL CHECK(skill BETWEEN 1 AND 100), state VARCHAR(24) NOT NULL, task_id UUID, lease_expires_at TIMESTAMPTZ, salary_minor BIGINT NOT NULL CHECK(salary_minor >= 0), version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE road_nodes (id UUID PRIMARY KEY, city_id UUID NOT NULL REFERENCES cities(id), world_id UUID NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, z INTEGER NOT NULL, node_type VARCHAR(24) NOT NULL, integrity SMALLINT NOT NULL CHECK(integrity BETWEEN 0 AND 100));
CREATE TABLE road_edges (id UUID PRIMARY KEY, from_node UUID NOT NULL REFERENCES road_nodes(id), to_node UUID NOT NULL REFERENCES road_nodes(id), distance DOUBLE PRECISION NOT NULL, capacity BIGINT NOT NULL, integrity SMALLINT NOT NULL CHECK(integrity BETWEEN 0 AND 100), UNIQUE(from_node,to_node));
CREATE TABLE shipments (id UUID PRIMARY KEY, origin_storage_id UUID NOT NULL, destination_storage_id UUID NOT NULL, manifest JSONB NOT NULL, route_id UUID, carrier_type VARCHAR(24) NOT NULL, status VARCHAR(32) NOT NULL, declared_value_minor BIGINT NOT NULL, insured_value_minor BIGINT NOT NULL DEFAULT 0, departed_at TIMESTAMPTZ, expected_arrival_at TIMESTAMPTZ, arrived_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0);

CREATE TABLE world_regions (id UUID PRIMARY KEY, region_key VARCHAR(64) NOT NULL UNIQUE, statistics JSONB NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE simulation_state (simulation_key VARCHAR(64) PRIMARY KEY, checkpoint_at TIMESTAMPTZ NOT NULL, state JSONB NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE world_events (id UUID PRIMARY KEY, region_id UUID REFERENCES world_regions(id), category VARCHAR(24) NOT NULL, event_key VARCHAR(64) NOT NULL, state VARCHAR(24) NOT NULL, state_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE kingdoms (id UUID PRIMARY KEY, name VARCHAR(48) NOT NULL UNIQUE, era VARCHAR(24) NOT NULL, prestige BIGINT NOT NULL DEFAULT 0, version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE kingdom_members (kingdom_id UUID NOT NULL REFERENCES kingdoms(id), city_id UUID NOT NULL REFERENCES cities(id), joined_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(kingdom_id, city_id), UNIQUE(city_id));
CREATE TABLE treaties (id UUID PRIMARY KEY, first_kingdom UUID NOT NULL REFERENCES kingdoms(id), second_kingdom UUID NOT NULL REFERENCES kingdoms(id), treaty_type VARCHAR(32) NOT NULL, status VARCHAR(24) NOT NULL, terms JSONB NOT NULL, expires_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0, CHECK(first_kingdom <> second_kingdom));
CREATE TABLE world_wonders (id UUID PRIMARY KEY, wonder_key VARCHAR(64) NOT NULL UNIQUE, kingdom_id UUID NOT NULL REFERENCES kingdoms(id), required_units BIGINT NOT NULL CHECK(required_units > 0), contributed_units BIGINT NOT NULL DEFAULT 0, status VARCHAR(24) NOT NULL, version BIGINT NOT NULL DEFAULT 0);

CREATE TABLE idempotency_tokens (id UUID PRIMARY KEY, actor_id UUID NOT NULL, action VARCHAR(64) NOT NULL, aggregate_id UUID, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ);
CREATE TABLE audit_log (id UUID PRIMARY KEY, actor_id UUID, action VARCHAR(64) NOT NULL, aggregate_type VARCHAR(40) NOT NULL, aggregate_id UUID, previous_value JSONB, new_value JSONB, reason TEXT, occurred_at TIMESTAMPTZ NOT NULL);
CREATE TABLE outbox_events (id UUID PRIMARY KEY, aggregate_type VARCHAR(40) NOT NULL, aggregate_id UUID NOT NULL, event_type VARCHAR(80) NOT NULL, payload JSONB NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, published_at TIMESTAMPTZ);
CREATE INDEX idx_outbox_pending ON outbox_events(occurred_at) WHERE published_at IS NULL;
