package nl.frontier.city;

public enum CityPermission {
  INVITE_MEMBER,
  REMOVE_MEMBER,
  PROMOTE_MEMBER,
  MANAGE_TREASURY,
  CLAIM_TERRITORY,
  MANAGE_BUILDINGS,
  START_REPAIR,
  MANAGE_WORKERS,
  DECLARE_WAR,
  ACCEPT_PEACE,
  CHANGE_TAXES,
  MANAGE_DISTRICTS,
  EDIT_SETTINGS
}
